name: scripts

on:
  push:
    branches:
    - 'main'
    - 'master'
    - 'dev'
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
    - '*'
  schedule:
    - cron: '0 22 */7 * *'  # every 7 days https://crontab.guru/#0_7_*_*_1
  workflow_dispatch:

jobs:
  build:
    name: scripts
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-latest]
    steps:
      - name: "📥 Checkout Code"
        uses: actions/checkout@v2.3.4
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: "✅ Check bash syntax"
        run: sudo make check
      - name: "✅ Check dependency"
        run: sudo make check-dep
      - name: "🛠️ Install"
        run: sudo make install
      - name: "🛠️ reinstall (optional)"
        run: sudo make reinstall
      - name: "🛠️ update (test)"
        run: sudo make update
      - name: "🧹 Uninstall"
        run: sudo make uninstall
      - name: "🛠️ build package"
        run: sudo make dist
      - name: "🛠️ build full package"
        run: sudo make dist-full