name: "tagged-release"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "📥 Checkout Code"
        uses: actions/checkout@v2.3.4
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: "✅ Check bash syntax"
        run: sudo make check
      - name: "🛠️ Install"
        run: sudo make install
      - name: "🧹 Uninstall"
        run: sudo make uninstall
      - name: "🛠️ build package"
        run: sudo make dist      
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.txt
            *.7z
